<?php

/**
 * @file
 * Contains mailgun.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mailgun_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mailgun module.
    case 'help.page.mailgun':

      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enables site to send emails using Mailgun.com') . '</p>';
      return $output;

    default:
  }
}
