<?php

/**
 * @file
 * Contains mailgun.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mailgun_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mailgun module.
    case 'help.page.mailgun':

      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enables site to send emails using Mailgun.com') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mailgun_theme($existing, $type, $theme, $path) {
  return array(
    'mailgun' => array(
      'variables' => array(
        'message' => array(),
      ),
      'mail theme' => TRUE,
    ),
  );
}

/**
 * Implements hook_theme_suggestions_HOOK() for mailgun.
 */
function mailgun_theme_suggestions_mailgun(array $variables) {
  $suggestions = [];
  $suggestions[] = 'mailgun';
  $suggestions[] = 'mailgun__' . $variables['message']['module'];
  $suggestions[] = 'mailgun__' . $variables['message']['module'] . '__' . $variables['message']['key'];
  return $suggestions;
}

/**
 * Prepares variables for mailgun templates.
 *
 * Default template: mailgun.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - message: An associative array containing the message array.
 *   - body: The processed body.
 */
function template_preprocess_mailgun(&$variables) {
  $variables['subject'] = $variables['message']['subject'];
  $variables['body'] = $variables['message']['body'];
}